---
platform: linux

image_resource:
  type: docker-image
  source: 
    repository: engineerbetter/pcf-ops

inputs:
- name: deploy_bosh
- name: tf_infra
- name: manifests
- name: state_bucket

outputs:
- name: outputs

run:
  path: deploy_bosh/bosh/deploy-bosh/ci/tasks/create_env.sh

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY: