---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

- name: concourse_pipeline
  type: docker-image
  source:
    repository: concourse/concourse-pipeline-resource

resources:
- name: tf_infra
  type: terraform
  icon: terraform
  source:
    env_name: deploy-bosh
    backend_type: s3
    backend_config:
      bucket: ((s3.bucket))
      key: ((s3.tf_state_path))
      region: ((s3.region))
      access_key: ((s3.access_key))
      secret_key: ((s3.secret_key))
    vars:
      region: ((infra.region))
      default_az: ((infra.az))
      source_ips: ((infra.source_ips))
    env:
      AWS_ACCESS_KEY_ID: ((infra.access_key))
      AWS_SECRET_KEY: ((infra.secret_key))
      AWS_DEFAULT_REGION: ((infra.region))

- name: deploy_bosh
  type: git
  icon: github-circle
  source:
    uri: ((gh_uri))
    paths: [bosh/deploy-bosh]

- name: manifests
  type: git
  icon: github-circle
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment.git

- name: this_pipeline
  type: concourse_pipeline
  icon: concourse-ci
  source:
    insecure: "true"
    target: ((ci.url))
    teams:
    - name: main
      username: ((ci.username))
      password: ((ci.password))

- name: director_state
  type: s3
  source:
    bucket: ((s3.bucket))
    access_key_id: ((s3.access_key))
    secret_access_key: ((s3.secret_key))
    region_name: ((s3.region))
    versioned_file: director-state
    initial_version: director-state

jobs:
- name: set_pipeline
  serial: true
  plan:
  - get: this_pipeline
  - get: deploy_bosh
    trigger: true
  - put: this_pipeline
    params:
      pipelines:
      - name: ((ci.pipeline))
        team: main
        config_file: deploy_bosh/bosh/deploy-bosh/ci/pipeline.yml

- name: deploy_infra
  serial: true
  serial_groups: [infra]
  plan:
  - get: deploy_bosh
    trigger: true
    passed: [set_pipeline]
  - put: tf_infra
    params:
      terraform_source: deploy_bosh/bosh/deploy-bosh/terraform/main
    
- name: destroy_infra
  serial: true
  serial_groups: [infra]
  plan:
  - get: deploy_bosh
    passed: [set_pipeline]
  - put: tf_infra
    params:
      action: destroy
      terraform_source: deploy_bosh/bosh/deploy-bosh/terraform/main
    get_params:
      action: destroy
    
- name: create_env
  serial: true 
  plan:
  - in_parallel:
    - get: manifests
    - get: deploy_bosh
      trigger: true
      passed: [deploy_infra]
    - get: tf_infra
      trigger: true
      passed: [deploy_infra]
    - get: director_state
  - task: create_env
    file: deploy_bosh/bosh/deploy-bosh/ci/tasks/create_env.yml
    params:
      AWS_ACCESS_KEY_ID: ((infra.access_key))
      AWS_SECRET_KEY: ((infra.secret_key))
  - put: director_state
    params:
      file: director-state
    