---
resources:
- name: react-app
  type: git
  icon: github-circle
  source:
    uri: https://github.com/irbekrm/learning-various.git
    paths:
    - docker/basics/react-app/client
jobs:
- name: run-tests
  plan:
  - get: react-app
    trigger: true
  - task: run-tests
    file: react-app/docker/basics/react-app/client/ci/run-tests.yml