---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node:alpine
    tag: latest

inputs:
- name: react-app

run:
  path: react-app/docker/basics/react-app/client/ci/run-tests.sh
  
params:
  CI: true