name: test
on: 
  push:
    branches:
      - "main"
    paths-ignore:
    - 'README.md'
    tags-ignore:
    - no_action
  workflow_dispatch: {}
defaults:
  run:
    shell: bash
jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: print-contents
      run: ls